### PR TITLE
+ greeting from Roman Saiko

### PR DESCRIPTION
**Pull request by RomanSaiko**
greeting from Roman Saiko

### CODE REVIEW

**Comment by nazmariam** [comment]
Hi! Seems like you code editor auto-formates .md files, you can see in "Files changed" tab that there are a lot of redundant indents. Please, turn off editor autoformating and make another commit

**Comment by RomanSaiko** [comment]
Hi!
I turned off autoformatter
Check please

**Review by miroslav-kolomiets — CHANGES_REQUESTED** [review]
Hi! But you did't revert that changes that was done before. If you go to https://github.com/kottans/mock-repo/pull/503/files and take a look at your changes, you'll see:
Снимок экрана 2020-10-26 в 8 46 53 PM
And others below.

**Review by miroslav-kolomiets — CHANGES_REQUESTED** [review]
Hi! Before send your PR to review, it's always good idea to have a look at your "File changed", as I wrote above (https://github.com/kottans/mock-repo/pull/503/files)

You removed everything from there, including your greeting and the blank line at the end of the file.

There should only be your greeting and nothing more.

**Comment by RomanSaiko** [comment]
It wasn`t a mistake. It wasn`t the last blank line of code, so I decided to remove it.

Make some changes to your local repository. It could be anything, really:
Including the blank line at the end of the file.

**Comment by RomanSaiko** [comment]
I know I pushed auto-formatted readme file.
I'll try to resolve it

**Comment by RomanSaiko** [comment]
I deleted previous commits using rebase
It seems PR autoclosed
So I reopened it, after new commit

**Review by MaxKalashnyk — APPROVED** [review]
Good job!

**Review by miroslav-kolomiets — APPROVED** [review]

**Pull request merged**
