### PR TITLE
Add small greetings

### PR DESCRIPTION
**Pull request by irishdra**

### CODE REVIEW

**Comment by irishdra** [comment]
there is a mistake, but it can be in order for those who want to fix it ;)

**Comment by lenadgit** [comment]
Hi Daryna, could you please add the image to your greeting? (according to this task)

**Comment by irishdra** [comment]
Add image! Thank you, I suddenly forgot about it :)

**Comment by irishdra** [comment]
> Hi Daryna, could you please add the image to your greeting? (according to this task)

done!

**Comment by lenadgit** [comment]
Great job!

**Pull request merged**
