### PR TITLE
Add greetings of NadiaVorontsova

### PR DESCRIPTION
**Pull request by NadiaVorontsova**
Add my greetings :)

### CODE REVIEW

**Comment by artem-trubin** [comment]
Hey Nadia! Nice job. Please resolve conflicts.

**Comment by NadiaVorontsova** [comment]
> Hey Nadia! Nice job. Please resolve conflicts.

Conflict resolved. Please check it :)

**Comment by artem-trubin** [comment]
Always check "Files changed" tab. You're trying to delete someones greeting! :o

**Comment by NadiaVorontsova** [comment]
> Always check "Files changed" tab. You're trying to delete someones greetings! :o

I fixed) please check it

**Comment by artem-trubin** [comment]
Nice!

**Pull request merged**
