### PR TITLE
Greetings

### PR DESCRIPTION
**Pull request by Lena-25**

### CODE REVIEW

**Review by lenadgit — CHANGES_REQUESTED** [review]
if you look at your commit - you will see changes, which were applied to other lines of this file. It means that your code-editor autoformatted it. How to avoid this issue - was mentioned here - [#460 (review)](https://github.com/kottans/mock-repo/pull/460#pullrequestreview-518209900)
Could you please fix it?

**Comment by Lena-25** [comment]
I don't have  check mark on auto-formatting settings like Format On Save in my redactor/IDE. So i don't know how to solve it.

**Comment by lenadgit** [comment]
> I don't have check mark on auto-formatting settings like Format On Save in my redactor/IDE. So i don't know how to solve it.

What editor or IDE do you use?

**Comment by Lena-25** [comment]
VS-code. I mean that i have option Format ON Save, but its not selected.

**Pull request closed without merging**
