### PR TITLE
New cat joined the team

### PR DESCRIPTION
**Pull request by MarharytaBoichenko**
Add  introduction and  new  image

### CODE REVIEW

**Comment by artem-trubin** [comment]
Hi! It seems that your text editor has some kind of autoformatting turned on. Please check your "Files changed" tab after applying changes in the PR.

**Comment by MarharytaBoichenko** [comment]
Thanks, I tried to  resolve.
I think  my  formatting  is because of this Editor: Format On Save Mode

**Comment by artem-trubin** [comment]
I don't think you fixed it)

**Comment by MarharytaBoichenko** [comment]
I don`t know  how to  fix that lines spaces because of  autoformatting(  I need to  change all  that lines by hand?

**Comment by artem-trubin** [comment]
You should google how to revert changes in git. That's what it's for!

**Comment by MarharytaBoichenko** [comment]
I`ve tried,  but it seems to me  I am  doing something wrong  after revert
I  revert  this  the first commit  [c265cce](https://github.com/kottans/mock-repo/pull/665/commits/c265cce13b24a553c3e8204c19a8384d455d2e8d)
then  I try  to  resolve conflict , revert  -continue   and  push  the  changes

**Comment by artem-trubin** [comment]
LGTM!

**Pull request merged**
