### PR TITLE
Update README.md H0us5

### PR DESCRIPTION
**Pull request by H0us5**

### CODE REVIEW

**Comment by artem-trubin** [comment]
Hi Bogdan! Please resolve conflicts.

**Comment by H0us5** [comment]
Hi! 'This branch has no conflicts with the base branch'

**Comment by artem-trubin** [comment]
Look at the bottom

image

**Comment by H0us5** [comment]
image
I resolve. and got this.

**Comment by artem-trubin** [comment]
Good job!

**Pull request merged**
