### PR TITLE
Added Greeting to all!

### PR DESCRIPTION
**Pull request by YuliaK2021**
Hi everyone! I've just made a pull request to the repo. Thanks for the opportunity to learn smth new)

### CODE REVIEW

**Comment by artem-trubin** [comment]
Welcome! Please resolve conflicts.

**Comment by YuliaK2021** [comment]
Resolved conflicts.

**Comment by YuliaK2021** [comment]
Thanks, done.

чт, 28 лип. 2022 р. о 21:48 Artem Trubin ***@***.***> пише:

**Comment by artem-trubin** [comment]
Good job!

**Pull request merged**
