### PR TITLE
update README.md 

### PR DESCRIPTION
**Pull request by vladyslavmaistruk**
Hi
This is my first PR
Looking forward to your merge

### CODE REVIEW

**Comment by artem-trubin** [comment]
Welcome, Vladyslav! Please resolve conflicts.

**Comment by vladyslavmaistruk** [comment]
Seems like resolved

**Comment by vladyslavmaistruk** [comment]
Hi, resolved new conflicts

**Comment by artem-trubin** [comment]
Good job!

**Pull request merged**
