### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by alieninochi**
Update readme.md

### CODE REVIEW

**Comment by suchov** [comment]
Hi, @alieninochi looks like you just started but already have conflicts. 
Do you want us to help you with them?

**Comment by alieninochi** [comment]
Hi!
I've already resolve the conflict, thank you.

**Comment by alieninochi** [comment]
Hi!
I've already resolved the conflict, thank you.

**Comment by suchov** [comment]
Merged, thank you!

**Pull request merged**
