### PR TITLE
Add greet to README.md

### PR DESCRIPTION
**Pull request by chernetskyi8704**

### CODE REVIEW

**Comment by artem-trubin** [comment]
Hi! Always check the PR after making one, you're trying to add a lot of changes. Probably because your autoformatter is on in the text editor. Make it so only your changes are present.

**Comment by chernetskyi8704** [comment]
Hi! Does this mean I have to remove absolutely everything from the README file and leave only what I added? I have read the articles on resolving conflicts and I understand that I have to remove the conflict markers and live only my changes, or am I mistaken? In practice, this is my first conflict and I'm afraid of doing something wrong. Thank you for your feedback.

**Comment by artem-trubin** [comment]
Look, you have changed the whole file by your autoformatter. That is what causing the troubles. You should google how to revert commits, revert those changes, then add your greeting again but without formatting on saving.

About conflicts: those appear when someone changed lines of code before you and you want to change those as well. In that moment, git cannot merge branches automatically and presents you with a choice. It stores both existing and incoming changes and marks them with those special markers. And you should decide yourself what exactly you want to leave. But first, you should figure out how to remove autoformatter changes.

**Comment by chernetskyi8704** [comment]
Okay, I think I got it. I sent another one, but again it is not correct. Thanks a lot

**Comment by chernetskyi8704** [comment]
Really can't figure out this. Trying to resolve one conflict and getting another one.  Getting just more complicated to understand of all this

**Comment by artem-trubin** [comment]
If it is getting this hard for you, you can use `git log` to view commits on your branch, search for a commit that was before any of your changes and use `git reset` on it. Than carefully add your changes. If you do this, git will not like that you "lost some commits" due to `git reset`. When you will push your changes, use `-f` flag to ignore those warnings.

**Pull request closed without merging**
