### PR TITLE
Firstbranch

### PR DESCRIPTION
**Pull request by filoxera1409**
Hello! Added my greeting and my cat's photo ^_^

### CODE REVIEW

**Comment by artem-trubin** [comment]
Hi, it seems that you have autoformatting turned on in your text editor. Please check "Files changed" tab and make sure only your greeting with a cat is there.

**Comment by filoxera1409** [comment]
Thanks. I`ve just updated the file)

**Comment by artem-trubin** [comment]
What I meant is that this PR should "add" only your greeting. Now you are "replacing" the whole file with your greeting.

**Comment by filoxera1409** [comment]
Re-created) Should be fine, I hope)

**Comment by artem-trubin** [comment]
Hi, I believe you are now deleted the whole file. You should "add" your lines, not "replace" the whole file with it.

**Comment by filoxera1409** [comment]
Hello) I started everything from the beginning (just lost my way in broad daylight :)))) and created new pull request https://github.com/kottans/mock-repo/pull/920

**Comment by suchov** [comment]
But it was already merged ))) so no 2nd chances )))

**Pull request closed without merging**
