### PR TITLE
Gongrat

### PR DESCRIPTION
**Pull request by GoncharovVV**
Git intro done http://prntscr.com/p5nblp

### CODE REVIEW

**Comment by yevhenorlov** [comment]
Hey @GoncharovVV , the master branch was changed and now you need to pull the changes and resolve the conflict. Let me know if you need help!

**Comment by GoncharovVV** [comment]
Conflicts fixed

**Comment by yevhenorlov** [comment]
almost there, take a look at the `Files changed` tab, looks like you've duplicated someone else's code (line 850): 
image

**Comment by GoncharovVV** [comment]
My bad )). Fixed

**Pull request merged**
