### PR TITLE
Dima Poberezhnyi

### PR DESCRIPTION
**Pull request by DinoDima666**
Nice to join you

### CODE REVIEW

**Comment by artem-trubin** [comment]
Hey Dima! Is there a reason you added your greeting using html markup and not markdown one? It is readme**.md** after all.

**Comment by DinoDima666** [comment]
Hey)
Sorry about this one, to be honest I've missed the part about the
markdown in .md files and used html cause I saw that it worked, but I've
already learned a proper mway to do it, so I'll be using it in the future.

**Comment by artem-trubin** [comment]
Nice! Welcome!

**Comment by DinoDima666** [comment]
Great! Thanks a lot ;)

**Pull request merged**
