### PR TITLE
add message from Irina to Kottans README

### PR DESCRIPTION
**Pull request by ivoinkova**
Sorry, I did wrong pull request a day ago. Now I do new pull request and add text and link to README.md instead of creating separate file. 
Thanks a lot for Kottans team attantion.

### CODE REVIEW

**Comment by OleksiyRudenko** [comment]
@ivoinkova NP. Good job!
However, repo's been updated since your PR submitted and there is a conflict now.
You need to update your branch from this repo's `master` and push your branch to update this your PR.
Will you?
If you need any help, please, let me know.

**Comment by ivoinkova** [comment]
Thanks for your reply. Maybe I need some help. 
 After I doing this commands 
- git checkout master
- git pull upstream master
- git merge upstream/master
I have the message **Everything up-to-date**, so I can not resolve conflict. 
** What did I do wrong? Can you help me or it better to do new pull request?**

**Comment by ivoinkova** [comment]
1. Screenshot [remote -v](https://github.com/kottans/frontend/blob/master/tasks/linux-cli-http.md)
2. Screenshot [graph history](https://github.com/ivoinkova/kottans-frontend/blob/master/img/branches.png)

**Comment by OleksiyRudenko** [comment]
@ivoinkova thanks, but first link leads to https://github.com/kottans/frontend/blob/master/tasks/linux-cli-http.md

Can you please just copy-paste output text here?

**Comment by ivoinkova** [comment]
$ git remote -v
origin  https://github.com/ivoinkova/mock-repo.git (fetch)
origin  https://github.com/ivoinkova/mock-repo.git (push)
upstream        https://github.com/ivoinkova/mock-repo.git (fetch)
upstream        https://github.com/ivoinkova/mock-repo.git (push)

**Comment by OleksiyRudenko** [comment]
@ivoinkova 
The `upstream` points at your own fork, that is why `git pull upstream` doesn't update from root repo `kottans/mock-repo`.
Replace `upstream` url with root repo url: `git remote set-url upstream https://github.com/kottans/mock-repo.git`

Everything should work since.

Let me know if the above helpful or you need any further support.

**Comment by AMashoshyna** [comment]
Hi @ivoinkova! Are you still working on this task? Do you need any help?

**Comment by AMashoshyna** [comment]
@ivoinkova I will close the PR for now. Feel free to reopen it whenever you are ready.

**Pull request closed without merging**
