### PR TITLE
Add new student

### PR DESCRIPTION
**Pull request by AndriiZahumnyi**
Add one more student, please!)

### CODE REVIEW

**Review by AndriiZahumnyi — COMMENTED** [review]
Sorry, this one not so correct, because of the kitty image, that 
shows not correct. This one have to be ignored. Thanks!

**Comment by Temu4** [comment]
Hi, good job! 
LGTM! 
The image you attached will be shown after merging.

**Review by miroslav-kolomiets — COMMENTED** [review]
Good job! In any case, you can change the picture in the same PR, there is no need to make a new one

**Comment by AndriiZahumnyi** [comment]
Add one more student - this one correct

**Comment by AndriiZahumnyi** [comment]
Sorry, but i can`t fix conflict yet... don`t know how...

**Comment by AndriiZahumnyi** [comment]
The conflict is fixed. Now everything`s alright. Thanks for your attention!

**Pull request closed without merging**
