### PR TITLE
Added new member Vitaliy-ol

### PR DESCRIPTION
**Pull request by vitaliy-ol**

### CODE REVIEW

**Comment by AMashoshyna** [comment]
Hi @vitaliy-ol ! Nice job, but I suggest to make your name a link to you profile on GitHub (using links in Markdown). Can you do that?

**Comment by vitaliy-ol** [comment]
Yes, of course)

**Comment by vitaliy-ol** [comment]
I made changes.  Everything is good?

**Comment by AMashoshyna** [comment]
Yes, nice work! LGTM

**Pull request merged**
