### PR TITLE
Here is my commit, where I added my name

### PR DESCRIPTION
**Pull request by yshvchnk**
I added my name in this pull request.

### CODE REVIEW

**Comment by suchov** [comment]
Hey @yshvchnk too many changes as per one pr -> [you can find them here](https://github.com/kottans/mock-repo/pull/1014/files)

**Comment by yshvchnk** [comment]
I resolved merge conflicts. But I can`t understand why there are so many changes. I tried to fix in my forked local repo, but it didn`t work. Maybe I can cancel my pull request and tried to do everything again? Because I have no ideas what else to do.

**Comment by suchov** [comment]
It's one of the options. But not to get in an issue like that in the future you can check the changes that you made before committing changes `git diff`...

**Comment by yshvchnk** [comment]
ok, thanks

**Comment by ElenaRiabova** [comment]
> Hey @yshvchnk too many changes as per one pr -> [you can find them here](https://github.com/kottans/mock-repo/pull/1014/files)

I have found them, np problem, but I can't change them

**Pull request closed without merging**
