### PR TITLE
My greetings to the Kottans!

### PR DESCRIPTION
**Pull request by natata-tutorial**

### CODE REVIEW

**Comment by suchov** [comment]
It looks wonderful.
The only thing can you pls move your lines under the comments with how to find help(the discord link).
Thank you!

**Comment by natata-tutorial** [comment]
Thnx for you reply)
Moved

**Comment by natata-tutorial** [comment]
Comment resolved. Please take another look)

**Comment by suchov** [comment]
Congrats, merged 🚀

**Pull request merged**
