### PR TITLE
Update REAME with introduce message

### PR DESCRIPTION
**Pull request by Aaarteem**

### CODE REVIEW

**Comment by artem-trubin** [comment]
Hey there! Please put a space between `##` and your header text so markdown header works correctly and resolve conflicts.

**Comment by artem-trubin** [comment]
Please don't delete PRs if you need to fix something. Fix it in here instead.

**Comment by Aaarteem** [comment]
Am I can't reopen this pull request if I made a force push?

**Comment by artem-trubin** [comment]
Yeah, it was you who closed it :D

**Pull request closed without merging**
