### PR TITLE
Just trying to work via command line

### PR DESCRIPTION
**Pull request by Vas-P**
Glad to join your community=)

### CODE REVIEW

**Review by suchov — APPROVED** [review]

**Review by miroslav-kolomiets — CHANGES_REQUESTED** [review]
Good job! But you need ti fix the conflict before we merge this PR ;)

**Comment by Vas-P** [comment]
I'll close this one, and add new pull request without making new branch.

**Comment by miroslav-kolomiets** [comment]
> I'll close this one, and add new pull request without making new branch.


What for? No need to close PR. It can all be done in one.

**Comment by Vas-P** [comment]
My mistake, i already reinstalled repo. So i'll make new pull request like i did it before.

**Pull request closed without merging**
