### PR TITLE
readme-upd

### PR DESCRIPTION
**Pull request by SkirnevskyiAleksandr**

### CODE REVIEW

**Review by lenadgit — CHANGES_REQUESTED** [review]
if you look at your commit - you will see changes, which were applied to other lines of this file.
https://github.com/kottans/mock-repo/pull/588/files
 It means that your code-editor autoformatted it. How to avoid this issue - was mentioned here - https://github.com/kottans/mock-repo/pull/460#pullrequestreview-518209900
Could you please fix it?

**Comment by SkirnevskyiAleksandr** [comment]
I did something wrong and now I don't know how to fix it. I'm going to close this pr and open a new one. Please tell me where I can see how I can make changes to an already created pool  request? Thank you!

**Comment by lenadgit** [comment]
Firstly you should set up your code-editor (or IDE) - to turn off autoformatting.
Then - get the recent changes from README (at command line type):
- git pull origin master
- (add your code (greeting) )
- git commit -m "commit"
- git push

**Comment by SkirnevskyiAleksandr** [comment]
First of all, thank you for your work and your patience)) (Tell me if I'm doing something wrong)
my steps:
1 git pull origin master;
2 git checkout redme-upd(my second branch);
3 git add . && git commit;
4 git merge master;
5 git push; (i pushing not "master" I pushing "readme-upd");

**Comment by SkirnevskyiAleksandr** [comment]
I think I found my mistake)))
I mixed up the "Readme-upd"&& "redmea-upd" branches (yes, now I know it was a bad idea with the branch names), and all my commits went to the other branch.

**Pull request closed without merging**
