### PR TITLE
Hello to everyone!

### PR DESCRIPTION
**Pull request by NatalyaBortsova**
I'm enjoyed to be in this community.

### CODE REVIEW

**Comment by artem-trubin** [comment]
Hi, Natalya. Is there a reason you used html markup and not markdown one?

**Comment by NatalyaBortsova** [comment]
Oh, yes. There is no reason, that's my mistake))

**Comment by artem-trubin** [comment]
Your current changes contain an incorrect header, please place space between `##` and header text for to work properly. Also, you are adding an image, but not using it.

**Comment by artem-trubin** [comment]
Well done!

**Pull request merged**
