### PR TITLE
One more commit

### PR DESCRIPTION
**Pull request by RuslanMozgovoi**
Please review)

### CODE REVIEW

**Review by miroslav-kolomiets — APPROVED** [review]
Good job!

**Comment by RuslanMozgovoi** [comment]
Hi Kottans,
My previous PR had conflicts due to unfetched commits of other students. I've updated my forked repo and this is new PR with no conflicts (I hope).

**Comment by RuslanMozgovoi** [comment]
Thank you, Miroslav)

**Comment by miroslav-kolomiets** [comment]
> Hi Kottans,
> My previous PR had conflicts due to unfetched commits of other students. I've updated my forked repo and this is new PR with no conflicts (I hope).


Everything is ok, but in the future, it is better to do this in one PR, there is no need to close the old one and open a new one. Just fix conflict in your branch, push it to github and it will update your PR ;)

**Comment by miroslav-kolomiets** [comment]
> Thank you, Miroslav)

It's my pleasure!

**Comment by RuslanMozgovoi** [comment]
> > Hi Kottans,
> > My previous PR had conflicts due to unfetched commits of other students. I've updated my forked repo and this is new PR with no conflicts (I hope).
> 
> Everything is ok, but in the future, it is better to do this in one PR, there is no need to close the old one and open a new one. Just fix conflict in your branch, push it to github and it will update your PR ;)

Thank you for the feedback, got it.

**Pull request merged**
