### PR TITLE
add new comment

### PR DESCRIPTION
**Pull request by Rybchynskyi**
I added a new comment at the beginning of the file

### CODE REVIEW

**Comment by Rybchynskyi** [comment]
I added a new comment at the beginning of the file

**Comment by artem-trubin** [comment]
There are a lot of changes, maybe it's autoformatter working. Are they intentional? If not, please remove them and only add your greeting.

**Comment by Rybchynskyi** [comment]
Done. Thant you!

**Comment by artem-trubin** [comment]
You deleted your PR, next time please try to resolve conflicts or fix mistakes in the same PR.

**Pull request closed without merging**
