### PR TITLE
add a new cat and update README.md

### PR DESCRIPTION
**Pull request by Nazar-cmd**

### CODE REVIEW

**Review by miroslav-kolomiets — CHANGES_REQUESTED** [review]
Hi, good job! But your PR affect other peoples code. These are the places where spaces are removed. Perhaps this is due to the settings of your code editor. This should be brought back, leaving only a greeting.

**Comment by Nazar-cmd** [comment]
Do I need also to resolve conflicts?

**Comment by miroslav-kolomiets** [comment]
> Do I need also to resolve conflicts?

Yes:)

**Comment by Nazar-cmd** [comment]
Thank you. Any wishes?)

**Review by miroslav-kolomiets — CHANGES_REQUESTED** [review]
Apparently, the conflict was not resolved correctly. There are now three greetings in the changes. It's always good to look at modified files. Only your code should be there.

**Pull request closed without merging**
