### PR TITLE
Second spherical branch

### PR DESCRIPTION
**Pull request by SphericalCat**

### CODE REVIEW

**Review by suchov — APPROVED** [review]

**Review by suchov — CHANGES_REQUESTED** [review]
Hmm, I thought I could resolve conflicts, but it looks like its too many of them.
694 lines changed ...

**Comment by suchov** [comment]
:'(

**Comment by suchov** [comment]
open up new one, it should be much easier now ;)

**Comment by SphericalCat** [comment]
Right now, I'm trying to do it. Thank you!

**Pull request closed without merging**
