### PR TITLE
Kottans

### PR DESCRIPTION
**Pull request by BogdanGapon**
Спустя 9  часов и удаления git у меня все таки вышло

### CODE REVIEW

**Comment by artem-trubin** [comment]
Welcome! Please check "Files changed" tab to make sure those are the changes that you want to make. It seems you have some kind of autoformatter turned on in your text editor.

**Comment by BogdanGapon** [comment]
i will change but now can`t to resolve problems

**Comment by BogdanGapon** [comment]
ready)

**Comment by artem-trubin** [comment]
Please open "Files changes" tab, theres 500+ changes there, not quite right :)

**Comment by BogdanGapon** [comment]
and how can i delete this all spaces ?

**Comment by artem-trubin** [comment]
You need to somehow revert those changes. You can google how it's done in git.

**Pull request closed without merging**
