### PR TITLE
added new cat

### PR DESCRIPTION
**Pull request by ded-git**

### CODE REVIEW

**Comment by artem-trubin** [comment]
What a nice cat you have there!

**Comment by artem-trubin** [comment]
That'll do, nice!

**Comment by artem-trubin** [comment]
Now, please resolve conflicts.

**Comment by ded-git** [comment]
but i didn't have conflicts at push time

чт, 21 лип. 2022 р. о 10:49 Artem Trubin ***@***.***> пише:

**Comment by artem-trubin** [comment]
These conflicts occured because someone made changes AFTER you pushed yours. That's a very common thing in repositories with big amounts of commits.

**Comment by artem-trubin** [comment]
Well done!

**Pull request merged**
