### PR TITLE
Create cat

### PR DESCRIPTION
**Pull request by ZjeniiaSt**

### CODE REVIEW

**Comment by artem-trubin** [comment]
Hi! I believe you have some sort of autoformatter turned on in your text editor. Please check "Files changed" tab after any changes and make sure that it's what you really want to add.

**Comment by artem-trubin** [comment]
Hey Zjeniia! It seems that you still have autoformatter problems. Please check "[Files Changed](https://github.com/kottans/mock-repo/pull/638/files)" to see what I mean.

**Comment by ZjeniiaSt** [comment]
Hello, this is the first time I encounter this. Is this a VSCode problem?

**Comment by artem-trubin** [comment]
It's not a "problem" it's just a feature that many text editor has, VSCode included. You need to revert those changes and if you don't want to turn autoformatter off (which is actually useful), you can just "Save without formatting". There is a separate command in VSCode for that.

**Comment by artem-trubin** [comment]
I understand that it seems easier to just close a PR here, delete branch and start over, but in real work you would ofter be facing times when you need to fix/revert changes in the same PR. It is fine now, but in the future please remain in the same PR.

**Comment by ZjeniiaSt** [comment]
Thanks for the tip!

чт, 21 лип. 2022 р. о 19:25 Artem Trubin ***@***.***> пише:

**Pull request closed without merging**
