### PR TITLE
Winter

### PR DESCRIPTION
**Pull request by SophiaPylypchuk**
New greatings

### CODE REVIEW

**Review by Shramkoweb — APPROVED** [review]

**Comment by lenadgit** [comment]
Hi Sofiya. Your picture is not displayed. That happened because the path to your picture is wrong - (img/cat.png)    There is no folder "img" in this repo. Correct path is (assets/images/your-picture). Could you please fix it?

**Review by miroslav-kolomiets — CHANGES_REQUESTED** [review]
And in addition to the above, you need to add this picture;)

**Comment by SophiaPylypchuk** [comment]
> Hi Sofiya. Your picture is not displayed. That happened because the path to your picture is wrong - (img/cat.png) There is no folder "img" in this repo. Correct path is (assets/images/your-picture). Could you please fix it?

Hi, Thank you for your answer. 
i made changes then commited. But in the end i got this

image

**Comment by AMashoshyna** [comment]
Looks like you are pushing your changes to the wrong upstream (to kottans/mock-repo directly). You need to push your commit to your fork (this will update the PR automatically)

**Comment by lenadgit** [comment]
Hi Sofia, a conflict was resolved, but your greeting is still without picture. ((img/cat.png)) Could you please fix it and push again? But do not forget make the pull before pushing (to avoid conflicts)

**Comment by SophiaPylypchuk** [comment]
> Looks like you are pushing your changes to the wrong upstream (to kottans/mock-repo directly). You need to push your commit to your fork (this will update the PR automatically)

Hi, really i don't know how to do what You are asking me :(.
The last command is pushing it to branch (winter) - my branch. Or I'm wrong? 
Could you please explain it to me what should i do. I'm stuck.
image

**Comment by babayK0** [comment]
@SophiaPylypchuk Seems like you made a typo ( missing `-`)

`git push --set upstream origin BRANCH_NAME` yours :red_circle: 

`git push --set-upstream origin BRANCH_NAME` correct :green_circle:

**Comment by babayK0** [comment]
@SophiaPylypchuk 
Also you made mistake when trying to execute this command
`git checkout winter && merge master` :red_circle: (need one more `git`)

`git checkout winter && git merge master` :green_circle:

**Review by babayK0 — APPROVED** [review]

**Comment by SophiaPylypchuk** [comment]
> @SophiaPylypchuk
> Also you made mistake when trying to execute this command
> `git checkout winter && merge master` 🔴 (need one more `git`)
> 
> `git checkout winter && git merge master` 🟢

Thank you very much! I should be more attentive

**Pull request merged**
