### PR TITLE
Feature/neskazhuk

### PR DESCRIPTION
**Pull request by Neskazhuk**
Git-intro done
Udacity done
Gi-it done

### CODE REVIEW

**Comment by artem-trubin** [comment]
Hi there!

Please do these things:
1. Use Markdown markup, not HTML one.
2. Don't add these screenshots here, they are meant to go to your personal `kottans-frontend` repo.
3. Resolve conflicts.

**Comment by Neskazhuk** [comment]
Hi, Artem! Fixed all of this. But don't know how to make new pull request.
Can help?

ср, 27 лип. 2022 р. о 19:03 Artem Trubin ***@***.***> пише:

**Comment by Neskazhuk** [comment]
Seems all of this was done. 
1. Rewrote my text using GitHub markdown instead of HTML
2. Deleted some previously added screenshots.
3. Resolved conflicts.
Thank you for your feedback!

**Comment by artem-trubin** [comment]
Please always check "Files changed" tab. It shows your current changes to the master branch. Make sure those are the changes you want to make.

**Comment by artem-trubin** [comment]
Look great to me! GJ!

**Pull request merged**
