### PR TITLE
add greeting and delete some spaces

### PR DESCRIPTION
**Pull request by drewzag**
hope this will work)

### CODE REVIEW

**Review by A-Ostrovnyy — CHANGES_REQUESTED** [review]
One of the main rules of this PR is don't touch the changes of other students, Please restore changes from other students and add just yours :grinning:

**Comment by drewzag** [comment]
I've resolved conflicts!

**Comment by drewzag** [comment]
> One of the main rules of this PR is don't touch the changes of other students, Please restore changes from other students and add just yours 😀

But I have no idea why GitHub shows a lot of changes made by me...
I add 2 lines (my greeting) and deleted just 2 or 3 blank lines

**Comment by A-Ostrovnyy** [comment]
@drewzag The problem was not only in conflicts but also in the fact that when you made your changes, you edited the lines of other students, this should not have been done) your PR should contain only your new changes without editing previous text.
image

**Comment by A-Ostrovnyy** [comment]
@drewzag when you save your changes your code editor makes these changes on save. 
1. You need to revert previous commits.
2. Add your changes and save file without formatting.
3. Push it and check the result)

**Comment by drewzag** [comment]
@A-Ostrovnyy should I close this PR?

**Comment by A-Ostrovnyy** [comment]
@drewzag Nope, just restore all changes and add new

**Review by A-Ostrovnyy — APPROVED** [review]
Awesome!

**Comment by drewzag** [comment]
🥳
Thanks)

**Pull request merged**
