### PR TITLE
Change readme file

### PR DESCRIPTION
**Pull request by CivilBitc4**

### CODE REVIEW

**Comment by artem-trubin** [comment]
Hi and welcome! Please remove arrows and other stuff that is not relevant for your message.

**Comment by artem-trubin** [comment]
You missed the last line.

**Comment by CivilBitc4** [comment]
Thanks.Now is right?

**Comment by artem-trubin** [comment]
Awesome!

**Comment by CivilBitc4** [comment]
Thank u so much )Good night:)

**Pull request merged**
