### PR TITLE
New kottan's soldier is on the way to become kottan master 88lvl

### PR DESCRIPTION
**Pull request by artellos747**

### CODE REVIEW

**Comment by artellos747** [comment]
I didn't really get what i should do. You mean i need to pull new file and send a pull request again or i needed to make a pull request using another branch ( not master)?

-- реклама -----------------------------------------------------------
Поторопись зарегистрировать самый короткий почтовый адрес @i.ua
https://mail.i.ua/reg - и получи 1Gb для хранения писем

**Comment by OleksiyRudenko** [comment]
@artellos747 yes, you need to come your fork, add this repo as an update remote, sync your fork pulling changes from upstream. At this point you will need to resolve a conflict. When done just push to your own fork and this pr will get updated automatically.

**Comment by artellos747** [comment]
> Hi @artellos747! Are you still working on this task? Do you need any help?

Hey ! I wanted to finish task 2 (about github) and solve it, but i forgot about this problem. Currently i'm finishing task 4 (responsive web design) and will solve this conflict. I think i know what to do, but if i have  problems/difficulties - i will here or in telegram of course. Ty for help)

**Comment by artellos747** [comment]
hi, so how is my answer? acceptable?

-- реклама -----------------------------------------------------------
Поторопись зарегистрировать самый короткий почтовый адрес @i.ua
https://mail.i.ua/reg - и получи 1Gb для хранения писем

**Pull request merged**
