### PR TITLE
Added greetings

### PR DESCRIPTION
**Pull request by ptalakh**
Added some greetings from myself

### CODE REVIEW

**Comment by A-Ostrovnyy** [comment]
One of the main rules of this PR is don't touch the changes of other students, Please restore changes from other students and add just yours :grinning: 
[Use this command](https://git-scm.com/docs/git-revert) to restore changes

**Comment by A-Ostrovnyy** [comment]
@ptalakh Why did you close this PR?

**Comment by ptalakh** [comment]
> @ptalakh Why did you close this PR?

Sorry, I was so confused by the branches and changes I did, that I couldn`t even explain what went wrong to get help and deleted repo both from the local storage and GitHub😞 
I found information about reverting merges, but I couldn't resolve merge (unmerge?) conflict and did some false commits who somehow changed another student changes in README. And I have also created one unnecessary branch
I can try to remake the task with creating another false merge and try to revert it

**Comment by A-Ostrovnyy** [comment]
@ptalakh Don't worry about that If you need help just ask in chat or we have a [discord](https://discord.gg/dqsQ9wss) server where we can fix your problem via screen sharing)

**Comment by ptalakh** [comment]
@A-Ostrovnyy Okay, thank you)

**Pull request closed without merging**
