### PR TITLE
README.md has changed

### PR DESCRIPTION
**Pull request by viktoriiab**
Hi, my name is Viktoriia, I am very glad to take a part on kottans courses. It is my first pull request.

### CODE REVIEW

**Comment by suchov** [comment]
@viktoriiab and you have a conflict ;) Can you solve it pls?

**Comment by viktoriiab** [comment]
I is solved?

**Comment by suchov** [comment]
@viktoriiab nope :)

**Comment by suchov** [comment]
or just someone was quicker than you

**Comment by suchov** [comment]
now looks nice!

**Pull request merged**
