### PR TITLE
One more greeting

### PR DESCRIPTION
**Pull request by eve5ince**

### CODE REVIEW

**Comment by lenadgit** [comment]
Could you please add the picture?

**Comment by eve5ince** [comment]
Hello! Thank you for reviewing. 
I added the picture, but it is said "This branch has conflicts that must be resolved. Only those with write access to this repository can merge pull requests."
Should I resolve the conflicts, or it is up to you?

**Comment by Temu4** [comment]
Hi Mykhaylo!
I believe that you should pull the latest updates from original repo and fix conflicts by yourself.

**Comment by eve5ince** [comment]
Hi, Artem! Thank you for reply.

**Comment by eve5ince** [comment]
accidentally spoiled everything...

**Comment by miroslav-kolomiets** [comment]
> accidentally spoiled everything...

It happens and it's normal. If you cannot solve something, write to the chat, we will always help;)

**Comment by eve5ince** [comment]
> > accidentally spoiled everything...
> 
> It happens and it's normal. If you cannot solve something, write to the chat, we will always help;)

Thanks a lot for such supportive reply! 
It is solved already=)

**Pull request closed without merging**
