### PR TITLE
send greeting to kottans

### PR DESCRIPTION
**Pull request by krylenger**
waiting forward to hear from you if you have any kind of feedback

### CODE REVIEW

**Review by miroslav-kolomiets — CHANGES_REQUESTED** [review]
Good job!
But you have some error with img `Non-Image content-type returned`

**Comment by nazmariam** [comment]
Now looks good!

**Review by Temu4 — CHANGES_REQUESTED** [review]
Looks good, but can you pull the latest changes from origin and fix conflicts?

**Review by miroslav-kolomiets — COMMENTED** [review]
Fix conflict and all is good)

**Comment by krylenger** [comment]
> Great!
Thanks!

@miroslav-kolomiets ,
just to double check: to proceed this pull request I should wait for approval from @Temu4 , right?

**Review by Temu4 — APPROVED** [review]
Sorry for late response. 
Looks good to me!

**Pull request merged**
