### PR TITLE
typo fix and leaving personal message

### PR DESCRIPTION
**Pull request by crlybrcs**
just doing what I have to :)

### CODE REVIEW

**Comment by artem-trubin** [comment]
Hi! Nice job finding typos! Can you please resolve conflicts?

**Comment by crlybrcs** [comment]
PR is updated. Conflict resolved.

**Comment by artem-trubin** [comment]
Always check your "Files changed" tab after making changes. It seems like you're removing some students' greetings.

**Comment by suchov** [comment]
@crlybrcs yeh, looks like you removed other student's greeting - you can check it here [Files changed](https://github.com/kottans/mock-repo/pull/722/files)

**Pull request closed without merging**
