### PR TITLE
First commit

### PR DESCRIPTION
**Pull request by maxovsanyuk**

### CODE REVIEW

**Comment by AMashoshyna** [comment]
Hi @maxovsanyuk! There have been changes to the repo and now your PR introduces a merge conflict. Please resolve it. Also, don't forget to put an empty line at the end of the file.

**Comment by AMashoshyna** [comment]
something is not right. With the last commit you deleted README.md all together. 
Hint: you can use `git revert <commit-hash>` to revert changes. Let me know if you need help

**Comment by maxovsanyuk** [comment]
Hell, I accidentally deleted README, so I solved that problem in that way 
    git reset --hard name of my previous commit  
    git push --force
What is your mind about that?

**Comment by AMashoshyna** [comment]
@maxovsanyuk In this particular case, where you commit changes to your own feature branch, it is completely acceptable. Generally it is assumed, that code in all branches except `master` and `develop` may change any time and other developers should wait until it is merged into `master`/`develop` to pull it.
For the cases where your code is already in `master`/`develop` and you need to change it you can use `git revert <commit SHA>`. Then both of your commits (initial one and correction) will remain in git history, but it's ok.

Also it's worth mentioning that project team usually decides what collaboration principles to use ([git flow](https://www.atlassian.com/git/tutorials/comparing-workflows/gitflow-workflow) it and example), so my suggestion may not apply for every team.

**Pull request merged**
