### PR TITLE
add readme files

### PR DESCRIPTION
**Pull request by DmytryjK**

### CODE REVIEW

**Comment by artem-trubin** [comment]
Hi, please make changed in the existing `readme.md` file, not in a new one.

**Comment by DmytryjK** [comment]
> Hi, please make changed in the existing `readme.md` file, not in a new one.

Can i change local readme file in fork kottans repo on my PC and doing again pull request? Or we have easier ways correct my mistakes?

**Comment by artem-trubin** [comment]
If you just push changes to the branch you created this PR from, they'll appear in this PR too. You don't need a new PR.

**Comment by DmytryjK** [comment]
Thx, i hope that i`m correct my mistake.

**Comment by artem-trubin** [comment]
Well done!

**Pull request merged**
