### PR TITLE
First commit for kottans) add text and gif readme.md

### PR DESCRIPTION
**Pull request by Karasb888**
new welcome message)

### CODE REVIEW

**Comment by yevhenorlov** [comment]
Great job, you're almost there!

Looks like master branch was updated since your last merge. Before I can merge your PR into master, you need to resolve the conflicts that are now present.
Let me know if you need help.

**Comment by yevhenorlov** [comment]
@Karasb888 You did a great job worth special recognition.

Here is your achievement badge:
[Kottans-Student-Gitignore%3D-mastered%20gitignore-orange.svg)](https://github.com/kottans/kottans/blob/master/endorsements.md)

Please, provide me with a link to a document in your repo so I could
PR the badge code into.

Congratulations on the skills level-up!

**Comment by Karasb888** [comment]
https://github.com/Karasb888/kottans-frontend You were talking about that
repo? (i just starting 😁 )


вс, 4 нояб. 2018 г. в 22:03, yevhen orlov <notifications@github.com>:

**Comment by Karasb888** [comment]
(*i am just starting) P.S. same for english)

вс, 4 нояб. 2018 г. в 22:43, Иван Мазуренко <ivan.mazurenko99@gmail.com>:

**Comment by Karasb888** [comment]
Also, i am sorry for 4+ commit in first task, i will try to keep clear my
repo commits history)

вс, 4 нояб. 2018 г. в 22:44, Иван Мазуренко <ivan.mazurenko99@gmail.com>:

**Comment by yevhenorlov** [comment]
Thanks! Check your repo, I've created a pull request.

> Also, i am sorry for 4+ commit in first task, i will try to keep clear my repo commits history)

That's ok, you're still learning!

**Pull request merged**
