### PR TITLE
add changes for commit task_git

### PR DESCRIPTION
**Pull request by pf4pad**
1. Completed the task of git .
2. Add doq's foto.
3. Created a pull request from my repository at https://github.com/kottans/mock-repo/
4. No conflicts found.

### CODE REVIEW

**Comment by artem-trubin** [comment]
Absence of conflicts sounds pretty strange, since you're adding 577 lines of code and deleting 306 :)

I believe you have autoformatter turned on. Please fix it so only your personal message is being added in this PR. You can use "Files Changed" tab to see your current changes.

**Comment by artem-trubin** [comment]
In the future, try to fix mistakes in the same PR, don't reopen a new one.

**Comment by pf4pad** [comment]
I tried but the prettier made too many changes

**Comment by artem-trubin** [comment]
You can revert those changes by using `git revert`. If you want to then save file without breaking everything you can use `Save without formatting` command in VSCode.

**Pull request closed without merging**
