### PR TITLE
taras-mavrovich-kottans: added light greeting

### PR DESCRIPTION
**Pull request by DarkSoulH**

### CODE REVIEW

**Comment by boxdxnx** [comment]
Oops, you need resolve conflicts first 😄

**Comment by DarkSoulH** [comment]
check as soon as possible

**Comment by artem-trubin** [comment]
Hi! Please check your "Files changed" tab in this PR and make sure these are the changes that you want to make.

**Comment by artem-trubin** [comment]
You don't need to close the PR every time you need to make changes. Just push them to the same branch and they'll appear in this PR.

**Pull request closed without merging**
