### PR TITLE
Adding my introduction to readme

### PR DESCRIPTION
**Pull request by AlexMosunov**
Adding my introduction to readme

### CODE REVIEW

**Comment by AMashoshyna** [comment]
Hi! Great job! Just one thing: was it intended that the whole text is formatted as header?

image

**Comment by AlexMosunov** [comment]
Hi! Thank you! Yeah, I used hash symbol # to make a header (similar to how other students did). Should have I used ## instead?

**Comment by AMashoshyna** [comment]
# is ok, but you need to put newline after the header (word "Hi" or exclamation mark, for example, so that the remaining test is normal size.

**Comment by AMashoshyna** [comment]
haha, yes, now I did the same mistake =))

**Comment by AlexMosunov** [comment]
ahah, got it! thanks:)

**Comment by AMashoshyna** [comment]
Perfect!

**Pull request merged**
