### PR TITLE
Add greetings fron another kottan, Myhkhailo

### PR DESCRIPTION
**Pull request by GeorgeWBoo**
please, merge, I'm begging you :)

### CODE REVIEW

**Review by lenadgit — CHANGES_REQUESTED** [review]
if you look at your commit - you will see changes, which were applied to other lines of this file. It means that your code-editor autoformatted it. How to avoid this issue - was mentioned here - https://github.com/kottans/mock-repo/pull/460#pullrequestreview-518209900
Could you please fix it?

**Comment by GeorgeWBoo** [comment]
> if you look at your commit - you will see changes, which were applied to other lines of this file.
> https://github.com/kottans/mock-repo/pull/587/files
> It means that your code-editor autoformatted it. How to avoid this issue - was mentioned here - [#460 (review)](https://github.com/kottans/mock-repo/pull/460#pullrequestreview-518209900)
> Could you please fix it?

@lenadgit thank you very much for your feedback. I've just fixed everything, could you check my latest commit with all the fixes?

**Comment by lenadgit** [comment]
> > if you look at your commit - you will see changes, which were applied to other lines of this file.
> > https://github.com/kottans/mock-repo/pull/587/files
> > It means that your code-editor autoformatted it. How to avoid this issue - was mentioned here - [#460 (review)](https://github.com/kottans/mock-repo/pull/460#pullrequestreview-518209900)
> > Could you please fix it?
> 
> @lenadgit thank you very much for your feedback.
> 
> I've just made my code-editor's settings back to normal, reverted to the commit when I had cloned my remote repo to the local one. Then I did all the procedure anew, resolved conflicts locally, and pushed everything back here.
> 
> Everything is supposed to work now, isn't it? What beats me is why the file 'README.md' in the 'Files changed' tab contains all that auto-corrections :(

Maybe the reason is conflict resolving?  I see that you removed a code on line 42  for example  https://github.com/kottans/mock-repo/pull/587/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L42

**Comment by GeorgeWBoo** [comment]
> > > if you look at your commit - you will see changes, which were applied to other lines of this file.
> > > https://github.com/kottans/mock-repo/pull/587/files
> > > It means that your code-editor autoformatted it. How to avoid this issue - was mentioned here - [#460 (review)](https://github.com/kottans/mock-repo/pull/460#pullrequestreview-518209900)
> > > Could you please fix it?
> > 
> > 
> > @lenadgit thank you very much for your feedback.
> > I've just made my code-editor's settings back to normal, reverted to the commit when I had cloned my remote repo to the local one. Then I did all the procedure anew, resolved conflicts locally, and pushed everything back here.
> > Everything is supposed to work now, isn't it? What beats me is why the file 'README.md' in the 'Files changed' tab contains all that auto-corrections :(
> 
> Maybe the reason is conflict resolving? I see that you removed a code on line 42 for example https://github.com/kottans/mock-repo/pull/587/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L42

@lenadgit This time I got rid of all red lines in the File changed tab. It seems like my branch is ready to be pulled :)

**Review by lenadgit — APPROVED** [review]
Well done! I hope you did it not manually)

**Pull request merged**
