### PR TITLE
Branch kot

### PR DESCRIPTION
**Pull request by mitko1717**

### CODE REVIEW

**Comment by lenadgit** [comment]
Every student must add the personal greeting in the end of the file (under previous greeting). According to documentation - the short greeting and the picture. See examples which were added by other students. The heading of README can not be changed. Could you please remove your changes and add your greeting again?

**Comment by mitko1717** [comment]
Hi. sorry for the mistake. i changed the README, and added the greeting.
and committed it in GitHab.

hope i did it right


вс, 25 окт. 2020 г. в 22:39, lenadgit <notifications@github.com>:

**Review by lenadgit — APPROVED** [review]

**Comment by lenadgit** [comment]
Yes, you fixed your mistake. But for further completing the task - should add your personal greeting - something like this "Hello,  etc"  and upload the picture - but below recent greetings in README.

**Comment by mitko1717** [comment]
but i added it already, and made my commit
e3d430f9e746797564ae501610cabeaa378d3852.
i dont understand whats wrong

пн, 26 окт. 2020 г. в 19:51, lenadgit <notifications@github.com>:

**Pull request closed without merging**
