### PR TITLE
Jack Loki came

### PR DESCRIPTION
**Pull request by ChukkyKatz**
Hi! Nice to meet you!

### CODE REVIEW

**Comment by AMashoshyna** [comment]
Hi @ChukkyKatz! You did a good job, however there seems to be a problem with link to image. Can you please fix it? No need to close this PR, you just need to push another commit to the same branch, and the PR will be updated.
Here is the problem:

image

**Comment by AMashoshyna** [comment]
can you also put a newline before the picture please?

image

**Comment by ChukkyKatz** [comment]
Yes, sure, I'll write comment when it be ready

**Comment by ChukkyKatz** [comment]
Now looks fine :)

**Comment by AMashoshyna** [comment]
Great, thanks!

**Pull request merged**
