### PR TITLE
Fix misspelling

### PR DESCRIPTION
**Pull request by tavor118sn**
New kottan is coming :tada:

### CODE REVIEW

**Review by lenadgit — CHANGES_REQUESTED** [review]
Good job!  But no need to correct a word at documentation. It was given for example only. Could you please revert your correction?

**Comment by tavor118sn** [comment]
@lenadgit Done

**Review by lenadgit — CHANGES_REQUESTED** [review]
But now as you see there is a conflict in your version of this file. It happened because other people made changes to this file too throughout this time. How to resolve it :
at command line type:
- git pull origin main
- git push
(for getting recent changes and pushing again)

**Comment by tavor118sn** [comment]
@lenadgit Hi! I've already done this  2 times :smile: 
Okay, will wait when this repo will be not updated so often

**Review by lenadgit — APPROVED** [review]
I see. I resolved it. It is good that it clear for you how it works and what for

**Pull request merged**
