### PR TITLE
new cat added

### PR DESCRIPTION
**Pull request by leoignis**

### CODE REVIEW

**Review by miroslav-kolomiets — CHANGES_REQUESTED** [review]
Hi! Nice work. But if you want your image to display, you have to add something like 
`my_kitten`
to README.md file in this repo ;)

**Comment by leoignis** [comment]
Hi! I tried to add a greeting and a picture to README.md

**Review by miroslav-kolomiets — CHANGES_REQUESTED** [review]
Nice work! All is well now. But conflicts need to be resolved.

**Comment by leoignis** [comment]
I'm trying to pull and merge to master branch but git answers that everything up to date already.Сould you, please, tell me some ideas on how to solve this problem because I don't understand what to do now

**Comment by AMashoshyna** [comment]
@leoignis Hi! Are you sure you are pulling from this repo and not from your fork? You can check with `git remote -v` to see which remotes (upstreams) you have now and then choose this repo to pull from.

**Pull request closed without merging**
