### PR TITLE
Lovely branch

### PR DESCRIPTION
**Pull request by Ivanna-Sivak**

### CODE REVIEW

**Review by miroslav-kolomiets — CHANGES_REQUESTED** [review]
Good job! But you have to resolve conflicts.

**Comment by Ivanna-Sivak** [comment]
Done!

**Comment by miroslav-kolomiets** [comment]
> Done!

Something went wrong, apparently not the correct resolve of merge conflict, there is other people's code in the changes, but only yours should be.

**Review by miroslav-kolomiets — CHANGES_REQUESTED** [review]
It seems that when resolving conflicts, your greeting was added in the middle of another greeting. Just add it to the end of the file and we will merge ;)
Снимок экрана 2020-10-31 в 12 17 48 AM

**Pull request closed without merging**
