### PR TITLE
Hello everyone!

### PR DESCRIPTION
**Pull request by AnnaStoyano**
Please review)

### CODE REVIEW

**Review by miroslav-kolomiets — CHANGES_REQUESTED** [review]
Good job! But if you want your picture to be visible in the README file, you should add something like that to README.md:
`# Hi!`
`Some optional text...`
`[name your image](gif/download.jpg)`

**Comment by Temu4** [comment]
> Good job! But if you want your picture to be visible in the README file, you should add something like that to README.md:
> `# Hi!`
> `Some optional text...`
> `[name your image](gif/download.jpg)`

Also don't forget to add `!` mark before embedded image link 👍 
`name your image`

**Comment by AnnaStoyano** [comment]
Thank you very much for your advice) I've tried to improve my work. Can you review it again?

**Comment by miroslav-kolomiets** [comment]
All in your changes is well now!)
But now you need to fix the conflict, just merge base branch into yours and update your pull request.

**Comment by AnnaStoyano** [comment]
Everything is good now? Thank you very much for help)))

**Comment by miroslav-kolomiets** [comment]
One small step remained. You moved your changes to the top of the document, this is not correct. It is better to place them in the same place as other greetings from participants;)

**Comment by AnnaStoyano** [comment]
I hope that now my commit is good. Thank you very much for your help and patience =)

**Review by miroslav-kolomiets — APPROVED** [review]
Good job!

**Pull request merged**
