### PR TITLE
Add description

### PR DESCRIPTION
**Pull request by vasylkomarnytskyi**
I added a section with my description to the README file.

### CODE REVIEW

**Comment by artem-trubin** [comment]
Hi and welcome! I believe, you have autoformatter turned on in your text editor, please do something with it. Check "Files changed" tab to make sure those are the right changes.

**Comment by vasylkomarnytskyi** [comment]
Hi. So, apparently, automatic formatting is turned on. Should I change the
file or leave everything as it was?

**Comment by artem-trubin** [comment]
You should make it so the formatting remains unchanged. So you need to revert your changes. It's up to you how exactly you want to do it. You can google `git revert` and `git reset` for info.

**Comment by vasylkomarnytskyi** [comment]
I seem to have turned off auto formatting. Can you please tell me if
everything is correct now.

**Comment by artem-trubin** [comment]
You can tell if anything is correct by inspecting this PR.

**Comment by vasylkomarnytskyi** [comment]
Please tell me, my branch was not merged because of some problems in it? I
apologize for bothering you so often.

**Comment by suchov** [comment]
@vasylkomarnytskyi, you can check it in the tab Files changed -> [this one](https://github.com/kottans/mock-repo/pull/678/files)

**Comment by suchov** [comment]
There are still the formating changes from your IDE, looks like too many changes for one small PR :)

**Pull request closed without merging**
