### PR TITLE
Task1

### PR DESCRIPTION
**Pull request by chernetskyi8704**

### CODE REVIEW

**Comment by zonzujiro** [comment]
You've deleted existing messages of other students. Please return them back :)

**Comment by chernetskyi8704** [comment]
I have revert my two committees, then updated the master using pull and added new changes to my branch, is it right? I just see that a lot of changes were made.

**Comment by chernetskyi8704** [comment]
Hi. I can not understand how to resolve such several conflicts at the same time. Either remove the markers, or leave only the bottom changes, or leave only the top changes. Somewhere text repeats, is not, somewhere just a lot weird of dashes and I can't figure out how to do it correctly, so as not to create new conflicts. I looked through all the training materials, and additional videos and never encountered an example for solving such several conflicts in one go.

**Comment by artem-trubin** [comment]
That _is_ the problem. You have to track those changes down and remove them, leaving only your greeting.

**Comment by chernetskyi8704** [comment]
Create new PR https://github.com/kottans/mock-repo/pull/900/

**Pull request closed without merging**
