### PR TITLE
edit

### PR DESCRIPTION
**Pull request by martoff1980**

### CODE REVIEW

**Comment by artem-trubin** [comment]
Hi Dmitry! Let's use a proper Markdown syntax to create a link, please!

**Comment by artem-trubin** [comment]
You didn't make a proper link and now you have some technical symbolls with arrows. Remove those please.

**Comment by artem-trubin** [comment]
Somehow everything got worse :)
Check "Files changed" tab to see it.

**Comment by artem-trubin** [comment]
Still no markdown link :)

You can wrap the link under your name using `[name](link)` for example.

**Comment by artem-trubin** [comment]
Hey, nice! Please remove HEAD and MASTER lines that appeared after resolving conflicts.

**Review by A-Ostrovnyy — APPROVED** [review]
Awesome!

**Pull request merged**
