### PR TITLE
Move greeting to the botoom of README.md

### PR DESCRIPTION
**Pull request by Lu-sure**

### CODE REVIEW

**Review by babayK0 — DISMISSED** [review]

**Comment by babayK0** [comment]
Please, resolve conflicts

**Comment by Lu-sure** [comment]
Done!

пн, 9 лист. 2020 о 20:58 Bohdan Kovalchuk <notifications@github.com> пише:

**Comment by babayK0** [comment]
sorry for my late reply. :crying_cat_face: 
unfortunately you must resolve conflicts again(

**Comment by Lu-sure** [comment]
Done, once more)

**Pull request merged**
