### PR TITLE
Dikun

### PR DESCRIPTION
**Pull request by YuliiaDikun**

### CODE REVIEW

**Comment by YuliiaDikun** [comment]
Solve the merge conflict.

**Comment by artem-trubin** [comment]
Hi! There is a strange empty file that you want to add. Can you please remove it?

**Comment by YuliiaDikun** [comment]
> Hi! There is a strange empty file that you want to add. Can you please remove it?

Hi! I delete the empty file.

**Comment by artem-trubin** [comment]
Good job!

**Pull request merged**
