### PR TITLE
Andrey kottans

### PR DESCRIPTION
**Pull request by zadorogniyandrey**
made changes to the readme and changed the branch name

### CODE REVIEW

**Comment by artem-trubin** [comment]
Hi there! Interesting choice to make html code in a markdown file :)

Can you make it so your link is an actualy markdown link, not just text? Use `[]()`.

**Comment by zadorogniyandrey** [comment]
Thanks! corrected the link

**Comment by artem-trubin** [comment]
First of all, you made a link like it's an html link. Please format it so it's a markdown link.

Also, it seems your autoformatter went out of controll. Please remove those changes, so only your greeting is added.

**Comment by zadorogniyandrey** [comment]
I hope everything is correct now)

**Comment by artem-trubin** [comment]
Everything is indeed correct. Good job!

**Pull request merged**
