### PR TITLE
My impressions about your powerful frontend course. I'm Andrey from Ekaterinburg. Good luck to everyone !)))

### PR DESCRIPTION
**Pull request by BlackFxTalon**
Hi, I'm young front-end developer. I've updated README.md, where I described my impressions about your course, and a gif ))

### CODE REVIEW

**Comment by BlackFxTalon** [comment]
Excuse me, I didn't understand you clearly. Where should I add a newline in the end? And what it's the LGTM? ))

**Comment by OleksiyRudenko** [comment]
A newline in the very end so that the file ends with an empty line and your addition won't be affected by further additions.

LGTM == Looks Good To Me

**Comment by OleksiyRudenko** [comment]
@BlackFxTalon Do you need any help with the above or any further clarifications?

**Comment by AMashoshyna** [comment]
Hi @BlackFxTalon! Are you still working on this task? Do you need any help?

**Comment by BlackFxTalon** [comment]
> Hi @BlackFxTalon! Are you still working on this task? Do you need any help?

Hi, unfortunately, not (( I'm too busy on my projects on this months right now... ((

**Comment by AMashoshyna** [comment]
@BlackFxTalon Thanks for reply! I will close the PR for now. Feel free to reopen it when you have time.

**Pull request closed without merging**
