### PR TITLE
andrey-kattans pull request

### PR DESCRIPTION
**Pull request by zadorogniyandrey**
Hello! Pleased to meet you! This is my first communication on github.

### CODE REVIEW

**Comment by artem-trubin** [comment]
Hi there! Please check your "Files changed" tab, and make sure those are the changes that you want to make. It seems like your text editor has some kind of autoformatter enabled.

**Comment by zadorogniyandrey** [comment]
Hi! I made changes

**Comment by artem-trubin** [comment]
Check "Files changed" tab please. I don't think you want to delete 2400 lines of someone's code :)

**Comment by zadorogniyandrey** [comment]
I thought only my code should be here

**Comment by artem-trubin** [comment]
Let's think logically. It is a huge readme.md where all students leave a couple of words about them as a greeting. You need to add such words from you, without harming the rest of the file. So only changes in this PR should be adding your lines, not affecting other lines.

**Pull request closed without merging**
