### PR TITLE
added image my bengal_cat.jpg in ./gif

### PR DESCRIPTION
**Pull request by vladyslavvorobei**
Last task of step 6 in part 1 "Git and GitHub": 
- [x] - make pull-request

I`m added my cat photo in your repo ^-^

### CODE REVIEW

**Review by miroslav-kolomiets — CHANGES_REQUESTED** [review]
Hi! Nice work. But if you want your image to display, you have to add something like
bengal_cat
to README.md file in this repo ;)

**Comment by Temu4** [comment]
- [ ] - make good PR)

**Comment by vladyslavvorobei** [comment]
> * [ ]  - зробити хороший PR)

- [x]  - зробити хороший PR)
Added my image to display id README.md file. 
Changed directory for image to ./assets/images

**Comment by Temu4** [comment]
Looks good to me! 👍 
But can you get the latest changes from origin repo and fix conflicts?

**Comment by vladyslavvorobei** [comment]
Everything is good?)

**Review by miroslav-kolomiets — APPROVED** [review]
Nice job!

**Pull request merged**
