### PR TITLE
Greetings to Kottans

### PR DESCRIPTION
**Pull request by WheatMan999**

### CODE REVIEW

**Review by miroslav-kolomiets — CHANGES_REQUESTED** [review]
Hi! Great job, but something went wrong with img, please check it
Снимок экрана 2020-10-14 в 1 52 13 PM

**Comment by WheatMan999** [comment]
Hi Miroslav, thanks for noticing that! The link was broken. Should be correct now.

**Comment by miroslav-kolomiets** [comment]
> Hi Miroslav, thanks for noticing that! The link was broken. Should be correct now.

Now all is great! just fix conflict, by merging master in your branch and we will merge this PR

**Comment by WheatMan999** [comment]
I've merged it (at least I think so)). Hope, everything is right.

**Review by miroslav-kolomiets — APPROVED** [review]
Good job!

**Pull request merged**
