### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Goralive**
Add greetings to Readme.md file

### CODE REVIEW

**Review by miroslav-kolomiets — CHANGES_REQUESTED** [review]
Good job! But there is a mistake, you have added two greetings. Perhaps these are the consequences of the merge. Please check again ;)

**Comment by Goralive** [comment]
Seems this is because of the merge. Should I create another commit? Or a new merge request?

**Comment by miroslav-kolomiets** [comment]
> Seems this is because of the merge. Should I create another commit? Or a new merge request?

No need to do new PR, just fix this one and make new commit.

**Comment by Goralive** [comment]
Update changes from main and add my 'hello' last

**Comment by Goralive** [comment]
Created new pull request

**Pull request closed without merging**
